---
- name: Package installation
  hosts: db
  ignore_errors: yes
#  gather_facts: no
  tasks:
   - name: Installing httpd package
     yum:
      name: httpd
      state: present
   - name: Installing wget package
     yum:
      name: wget
      state: presnt
     #ignore_errors: yes
- name: Package installation in node5
  hosts: node5
  ignore_errors: yes
  tasks:
   - name: Installing wget
     yum:
      name: wget
      state: presnt
